<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Lab13Web_NadiaTorres.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
      <PackageReference Include="MediatR" Version="13.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UseCases\OrderdetailUseCase\Commands\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lab13Web-NadiaTorres.Domain\Lab13Web-NadiaTorres.Domain.csproj" />
    </ItemGroup>

</Project>
